DB_PATH = "../db.db"
MOVIES_TABLE = "movies"
FEATURES = [
    "Popularity",
    "Vote Count",
    "Runtime",
    "Release Year",
    "Language: English",
    "Actor: Samuel L Jackson",
    "Actor: Morgan Freeman",
    "Actor: John Ratzenberger",
    "Actor: Tom Hanks",
    "Actor: Robert De Niro",
    "Actor: Harrison Ford",
    "Actor: Leonardo DiCaprio",
    "Actor: Matt Damon",
    "Actor: Brad Pitt",
    "Actor: Christian Bale",
    "Actor: Michael Caine",
    "Actor: Gany Oldman",
    "Actor: Paul Giamatti",
    "Actor: Michael Gambon",
    "Actor: Robert Duvall",
    "Genre: Action",
    "Genre: Advventure",
    "Genre: Animation",
    "Genre: Comedy",
    "Genre: Crime",
    "Genre: Documentary",
    "Genre: Drama",
    "Genre: Family",
    "Genre: Fatnasy",
    "Genre: Foreign",
    "Genre: History",
    "Genre: Horror",
    "Genre: Music",
    "Genre: Mystery",
    "Genre: Romance",
    "Genre: Science Fiction",
    "Genre: TV Movie",
    "Genre: Thriller",
    "Genre: War",
    "Genre: Western",
    "Studio: Warner Bros",
    "Studio: Universal Pictures",
    "Studio: Paramount Pictures",
    "Studio: Twentieth Century Fox Film Corporation",
    "Studio: United Artists",
    "Studio: New Line Cinema",
    "Studio: Walt Disney Pictures",
    "Studio: Columbia Pictures",
    "Studio: Miramax Films",
    "Studio: Canal+",
    "Studio: Columbia Pictures Corporation",
    "Studio: Metro Goldwyn Mayer (MGM)",
    "Studio: Film4",
    "Studio: Amblin Entertainment",
    "Studio: Touchstone Pictures",
    "Director: Steven Spielberg",
    "Director: Martin Scorsese",
    "Director: Quentin Tarantino",
    "Director: Christopher Nolan",
    "Director: Clint Eastwood",
    "Director: Unknown",
    "Director: Wes Anderson",
    "Director: Ridley Scott",
    "Director: Richard Linklater",
    "Director: Francis Ford Coppola",
    "Director: Hayao Miyazaki",
    "Director: David Fincher",
    "Keyword: Based On Novel",
    "Keyword: Independent Film",
    "Keyword: Woman Director",
    "Keyword: During Credits Stinger",
    "Keyword: Dystopia",
    "Keyword: Biography",
    "Keyword: World War II",
    "Keyword: Friendship",
    "Keyword: Love",
    "Keyword: After Credits Stinger",
    "Keyword: Violence",
    "Keyword: War",
    "Keyword: Dying And Death",
    "Keyword: Murder",
    "Keyword: Sport",
    "Keyword: Musical",
    "Keyword: Magic",
    "Keyword: Revenge",
    "Keyword: Nazis",
    "Keyword: Based On True Story",
    "Country: United States Of America",
    "Country: United Kingdom",
    "Country: Germany",
    "Country: France",
    "Country: Canada"
]
CLASSES = [
    "No Recommend",
    "Recommend"
]